@extends('layouts.admin')

@section('title', 'مدیریت کل EarthCoop - نجم هدا')
@section('page-title', 'Founder Operations')
@section('page-description', 'مرکز یکپارچهٔ مدیریت کل EarthCoop توسط نجم هدا')

@section('content')
<div class="container-fluid py-3" dir="rtl">
    @if(session('success'))<div class="alert alert-success">{{ session('success') }}</div>@endif
    @if(session('error'))<div class="alert alert-danger">{{ session('error') }}</div>@endif

    <div class="d-flex flex-wrap justify-content-between align-items-center gap-2 mb-4">
        <div><h4 class="mb-1">گزارش مدیریتی نجم هدا</h4><div class="text-muted small">بازه گزارش: {{ $hours }} ساعت اخیر</div></div>
        <div class="btn-group">@foreach([6,24,72,168] as $window)<a href="{{ route('admin.najm-hoda.founder-ops.index',['hours'=>$window]) }}" class="btn btn-sm {{ $hours===$window?'btn-primary':'btn-outline-secondary' }}">{{ $window }} ساعت</a>@endforeach</div>
    </div>

    @php
        $summary=data_get($brief,'summary',[]); $authority=data_get($brief,'authority',[]);
        $founderApprovals=$approvalInbox ?? data_get($brief,'founder_approvals',[]); $coverage=data_get($brief,'management_coverage',[]);
        $approvalItems=collect(data_get($founderApprovals,'items',[]));
        $supportApprovalItems=$approvalItems->filter(fn($i)=>data_get($i,'domain')==='support' && data_get($i,'domain_action')==='send_reply');
        $referenceApprovalItems=$approvalItems->filter(fn($i)=>in_array(data_get($i,'domain'),['reference_data','locations'],true) && data_get($i,'domain_action')==='approve');
        $moderationApprovalItems=$approvalItems->filter(fn($i)=>data_get($i,'domain')==='reports_moderation' && data_get($i,'domain_action')==='resolve_report');
    @endphp

    <div class="row g-3 mb-4">
        @foreach([['P0','بحرانی'],['P1','نیازمند تصمیم'],['P2','صف کار'],['P3','اطلاعات']] as [$key,$label])<div class="col-6 col-md-3"><div class="card h-100"><div class="card-body"><div class="text-muted small">{{ $label }} {{ $key }}</div><div class="fs-3 fw-bold">{{ data_get($summary,$key,0) }}</div></div></div></div>@endforeach
    </div>

    <div class="row g-3 mb-4">
        <div class="col-lg-8"><div class="card h-100"><div class="card-header d-flex justify-content-between"><strong>موارد نیازمند توجه</strong><span class="badge bg-secondary">{{ data_get($summary,'total_attention_items',0) }} مورد</span></div><div class="list-group list-group-flush">@forelse(data_get($brief,'items',[]) as $item)<div class="list-group-item"><div class="d-flex justify-content-between gap-3"><div><div class="fw-semibold">{{ data_get($item,'title') }}</div><div class="small text-muted">دامنه: {{ data_get($item,'domain') }}</div></div><span class="badge bg-secondary">{{ data_get($item,'priority') }}</span></div></div>@empty<div class="list-group-item text-muted">موردی برای توجه ثبت نشده است.</div>@endforelse</div></div></div>
        <div class="col-lg-4"><div class="card mb-3"><div class="card-header"><strong>صف تأیید Founder</strong></div><div class="card-body"><div class="d-flex justify-content-between mb-2"><span>منتظر تأیید</span><strong>{{ data_get($founderApprovals,'pending',0) }}</strong></div><div class="d-flex justify-content-between mb-2"><span>عقب‌افتاده از SLA</span><strong>{{ data_get($founderApprovals,'overdue',0) }}</strong></div><div class="d-flex justify-content-between"><span>داخل SLA</span><strong>{{ data_get($founderApprovals,'within_sla',0) }}</strong></div></div></div><div class="card"><div class="card-header"><strong>حدود اختیار نجم هدا</strong></div><div class="card-body"><div>Actionهای تعریف‌شده: <strong>{{ data_get($authority,'total_actions',0) }}</strong></div><div>Delegation فعال: <strong>{{ data_get($authority,'active_delegations_count',0) }}</strong></div><div>Fail-closed: <strong>{{ data_get($authority,'fail_closed')?'بله':'خیر' }}</strong></div></div></div></div>
    </div>

    <div class="card mb-4"><div class="card-header d-flex justify-content-between"><strong>پیش‌نویس‌های پاسخ پشتیبانی</strong><span class="badge bg-secondary">{{ count($supportDrafts ?? []) }}</span></div><div class="card-body p-0"><div class="table-responsive"><table class="table table-hover align-middle mb-0"><thead><tr><th>تیکت</th><th>موضوع</th><th>پیش‌نویس نجم هدا</th><th>اقدام</th></tr></thead><tbody>@forelse($supportDrafts ?? [] as $draft)<tr><td>{{ $draft->ticket?->tracking_code ?? '#'.$draft->ticket_id }}</td><td>{{ $draft->ticket?->subject ?? '-' }}</td><td style="min-width:320px;max-width:620px;white-space:pre-wrap">{{ $draft->body }}</td><td><form method="POST" action="{{ route('admin.najm-hoda.founder-ops.support-drafts.request-send',$draft) }}">@csrf<button class="btn btn-sm btn-outline-primary">درخواست تأیید ارسال</button></form></td></tr>@empty<tr><td colspan="4" class="text-muted text-center py-3">پیش‌نویس بازی وجود ندارد.</td></tr>@endforelse</tbody></table></div></div></div>

    @if($supportApprovalItems->isNotEmpty())<div class="card mb-4 border-warning"><div class="card-header"><strong>تصمیم‌های ارسال پاسخ منتظر شما</strong></div><div class="card-body">@foreach($supportApprovalItems as $approval)<div class="d-flex flex-wrap justify-content-between align-items-center gap-2 border-bottom py-2"><div><div class="fw-semibold">درخواست {{ data_get($approval,'id') }}</div><div class="small text-muted">Draft #{{ data_get($approval,'context.entity_id') }} · {{ data_get($approval,'sla_status') }}</div></div><div class="d-flex gap-2"><form method="POST" action="{{ route('admin.najm-hoda.founder-ops.support-approvals.decision',data_get($approval,'id')) }}">@csrf<input type="hidden" name="decision" value="approve"><button class="btn btn-sm btn-success">تأیید و ارسال</button></form><form method="POST" action="{{ route('admin.najm-hoda.founder-ops.support-approvals.decision',data_get($approval,'id')) }}">@csrf<input type="hidden" name="decision" value="reject"><button class="btn btn-sm btn-outline-danger">رد</button></form></div></div>@endforeach</div></div>@endif

    <div class="card mb-4"><div class="card-header d-flex justify-content-between"><strong>صف تأیید مکان / صنف / تخصص با بررسی تکراری</strong><span class="badge bg-secondary">{{ count($referenceCandidates ?? []) }}</span></div><div class="card-body p-0"><div class="table-responsive"><table class="table table-sm align-middle mb-0"><thead><tr><th>نوع</th><th>عنوان</th><th>ریسک تکرار</th><th>موارد مشابه</th><th>پیشنهاد</th><th>اقدام</th></tr></thead><tbody>@forelse($referenceCandidates ?? [] as $candidate)<tr><td>{{ data_get($candidate,'type') }}</td><td>{{ data_get($candidate,'name') }}</td><td><span class="badge bg-{{ data_get($candidate,'duplicate_risk')==='high'?'danger':(data_get($candidate,'duplicate_risk')==='medium'?'warning':'success') }}">{{ data_get($candidate,'duplicate_risk') }}</span></td><td>@forelse(data_get($candidate,'similar',[]) as $similar)<div>{{ data_get($similar,'name') }} <small class="text-muted">{{ round(data_get($similar,'similarity',0)*100) }}%</small></div>@empty<span class="text-muted">مورد نزدیک پیدا نشد</span>@endforelse</td><td>{{ data_get($candidate,'recommendation') }}</td><td><form method="POST" action="{{ route('admin.najm-hoda.founder-ops.reference.request-approve',['type'=>data_get($candidate,'type'),'id'=>data_get($candidate,'id')]) }}">@csrf<button class="btn btn-sm {{ data_get($candidate,'duplicate_risk')==='high'?'btn-outline-warning':'btn-outline-success' }}">درخواست تأیید</button></form></td></tr>@empty<tr><td colspan="6" class="text-muted text-center py-3">مورد منتظر تأییدی وجود ندارد.</td></tr>@endforelse</tbody></table></div></div></div>

    @if($referenceApprovalItems->isNotEmpty())<div class="card mb-4 border-info"><div class="card-header"><strong>تأیید داده‌های پایه منتظر تصمیم شما</strong></div><div class="card-body">@foreach($referenceApprovalItems as $approval)<div class="d-flex flex-wrap justify-content-between align-items-center gap-2 border-bottom py-2"><div><div class="fw-semibold">{{ data_get($approval,'context.entity_type') }} #{{ data_get($approval,'context.entity_id') }}</div><div class="small text-muted">{{ data_get($approval,'sla_status') }}</div></div><div class="d-flex gap-2"><form method="POST" action="{{ route('admin.najm-hoda.founder-ops.reference-approvals.decision',data_get($approval,'id')) }}">@csrf<input type="hidden" name="decision" value="approve"><button class="btn btn-sm btn-success">تأیید نهایی</button></form><form method="POST" action="{{ route('admin.najm-hoda.founder-ops.reference-approvals.decision',data_get($approval,'id')) }}">@csrf<input type="hidden" name="decision" value="reject"><button class="btn btn-sm btn-outline-secondary">فعلاً تأیید نشود</button></form></div></div>@endforeach</div></div>@endif

    <div class="card mb-4"><div class="card-header d-flex justify-content-between"><strong>پرونده‌های Moderation آماده بررسی</strong><span class="badge bg-secondary">{{ count($moderationCases ?? []) }}</span></div><div class="card-body p-0"><div class="table-responsive"><table class="table table-sm align-middle mb-0"><thead><tr><th>منبع</th><th>دسته</th><th>شدت</th><th>خلاصه نجم هدا</th><th>اقدام</th></tr></thead><tbody>@forelse($moderationCases ?? [] as $case)<tr><td>{{ $case->source_type }} #{{ $case->source_id }}</td><td>{{ $case->classification }}</td><td><span class="badge bg-{{ $case->severity==='high'?'danger':'warning' }}">{{ $case->severity }}</span></td><td style="min-width:320px;max-width:620px;white-space:pre-wrap">{{ $case->summary }}</td><td><form method="POST" action="{{ route('admin.najm-hoda.founder-ops.moderation.request-resolve',['sourceType'=>$case->source_type,'sourceId'=>$case->source_id]) }}">@csrf<button class="btn btn-sm btn-outline-primary">درخواست حل گزارش</button></form></td></tr>@empty<tr><td colspan="5" class="text-muted text-center py-3">پرونده آماده‌ای وجود ندارد.</td></tr>@endforelse</tbody></table></div></div></div>

    @if($moderationApprovalItems->isNotEmpty())<div class="card mb-4 border-danger"><div class="card-header"><strong>تصمیم‌های Moderation منتظر شما</strong></div><div class="card-body">@foreach($moderationApprovalItems as $approval)<div class="d-flex flex-wrap justify-content-between align-items-center gap-2 border-bottom py-2"><div><div class="fw-semibold">{{ data_get($approval,'context.entity_type') }} #{{ data_get($approval,'context.entity_id') }}</div><div class="small text-muted">{{ data_get($approval,'sla_status') }}</div></div><div class="d-flex gap-2"><form method="POST" action="{{ route('admin.najm-hoda.founder-ops.moderation-approvals.decision',data_get($approval,'id')) }}">@csrf<input type="hidden" name="decision" value="approve"><button class="btn btn-sm btn-success">تأیید حل گزارش</button></form><form method="POST" action="{{ route('admin.najm-hoda.founder-ops.moderation-approvals.decision',data_get($approval,'id')) }}">@csrf<input type="hidden" name="decision" value="reject"><button class="btn btn-sm btn-outline-danger">رد درخواست</button></form></div></div>@endforeach</div></div>@endif

    <div class="card mb-4"><div class="card-header d-flex justify-content-between"><strong>پیشنهادهای پیگیری دبیرخانه</strong><span class="badge bg-secondary">{{ count($secretariatFollowUps ?? []) }}</span></div><div class="card-body p-0"><div class="table-responsive"><table class="table table-sm align-middle mb-0"><thead><tr><th>شماره ثبت</th><th>Dispatch</th><th>فوریت</th><th>پیشنهاد نجم هدا</th></tr></thead><tbody>@forelse($secretariatFollowUps ?? [] as $proposal)<tr><td>{{ $proposal->dispatch?->record?->registry_number ?? '-' }}</td><td>#{{ $proposal->dispatch_id }} · {{ $proposal->dispatch?->status }}</td><td><span class="badge bg-{{ $proposal->urgency==='high'?'danger':'secondary' }}">{{ $proposal->urgency }}</span></td><td style="min-width:360px;white-space:pre-wrap">{{ $proposal->proposal }}</td></tr>@empty<tr><td colspan="4" class="text-muted text-center py-3">پیگیری آماده‌ای وجود ندارد.</td></tr>@endforelse</tbody></table></div><div class="small text-muted p-3">این بخش فقط پیشنهاد پیگیری است؛ هیچ ارسال یا تغییر وضعیت رسمی دبیرخانه از اینجا انجام نمی‌شود.</div></div></div>

    <div class="row g-3 mb-4"><div class="col-md-4"><div class="card h-100"><div class="card-header"><strong>کاربران</strong></div><div class="card-body"><div>جدید: {{ data_get($snapshot,'users.new_members',0) }}</div><div>تأیید ایمیل‌شده: {{ data_get($snapshot,'users.new_verified_members',0) }}</div></div></div></div><div class="col-md-4"><div class="card h-100"><div class="card-header"><strong>پشتیبانی</strong></div><div class="card-body"><div>باز: {{ data_get($snapshot,'support.open',0) }}</div><div>بدون مسئول: {{ data_get($snapshot,'support.unassigned_active',0) }}</div><div>مهم: {{ data_get($snapshot,'support.high_priority_active',0) }}</div></div></div></div><div class="col-md-4"><div class="card h-100"><div class="card-header"><strong>تأیید داده پایه</strong></div><div class="card-body"><div>صنف/تخصص: {{ data_get($snapshot,'approvals.references.total',0) }}</div><div>مکان: {{ data_get($snapshot,'approvals.locations.total',0) }}</div></div></div></div></div>

    <div class="card"><div class="card-header"><strong>پوشش مدیریت یکپارچه</strong></div><div class="card-body"><div class="d-flex flex-wrap gap-4"><div>کل دامنه‌ها: <strong>{{ data_get($coverage,'counts.total',0) }}</strong></div><div>Observed: <strong>{{ data_get($coverage,'counts.observed',0) }}</strong></div><div>Managed: <strong>{{ data_get($coverage,'counts.managed',0) }}</strong></div><div>پوشش: <strong>{{ data_get($coverage,'integration_coverage_percent',0) }}%</strong></div></div></div></div>
</div>
@endsection